{
  "openapi": "3.0.3",
  "servers": [
    {
      "url": "https://spotdx.com",
      "description": "Production"
    }
  ],
  "info": {
    "title": "Spot API v2",
    "version": "2.0.0",
    "description": "API Docs for Spot API"
  },
  "paths": {
    "/api/v2/kits/": {
      "get": {
        "operationId": "api_v2_list_kits",
        "description": "Query your kits and return a summary, sorted by creation date. Providing any query params will further filter the results to only those that match the query params.",
        "parameters": [
          {
            "in": "query",
            "name": "results",
            "description": "Number of results to return per page.",
            "schema": {
              "type": "integer",
              "minimum": 1,
              "maximum": 100
            }
          },
          {
            "in": "query",
            "name": "offset",
            "description": "The initial index from which to return the results.",
            "schema": {
              "type": "integer",
              "minimum": 0
            },
            "required": false
          },
          {
            "in": "query",
            "name": "email",
            "schema": {
              "type": "string"
            },
            "description": "Only retrieve kits associated with this email address. Case insensitive."
          },
          {
            "in": "query",
            "name": "first_name",
            "schema": {
              "type": "string"
            },
            "description": "Only retrieve kits associated with this first name. Case insensitive."
          },
          {
            "in": "query",
            "name": "kit_type",
            "schema": {
              "type": "string"
            },
            "description": "Only retrieve kits associated with this kit type."
          },
          {
            "in": "query",
            "name": "last_name",
            "schema": {
              "type": "string"
            },
            "description": "Only retrieve kits associated with this last name. Case insensitive."
          },
          {
            "in": "query",
            "name": "phone",
            "schema": {
              "type": "string"
            },
            "description": "Only retrieve kits associated with this phone number."
          },
          {
            "in": "query",
            "name": "kit_status",
            "schema": {
              "$ref": "#/components/schemas/KitStatus"
            },
            "description": "Only retrieve kits whose most recent event is this status."
          },
          {
            "in": "query",
            "name": "sample_status",
            "schema": {
              "$ref": "#/components/schemas/SampleStatus"
            },
            "description": "Only retrieve kits whose sample's most recent event is this status."
          },
          {
            "in": "query",
            "name": "order_id",
            "schema": {
              "type": "string"
            },
            "description": "Get kits belonging to a specified order ID"
          }
        ],
        "security": [
          {
            "tokenAuth": []
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "kit_id": {
                        "type": "string"
                      },
                      "kit_type": {
                        "type": "string"
                      },
                      "order_id": {
                        "type": "string"
                      },
                      "kit_status": {
                        "$ref": "#/components/schemas/KitStatus"
                      },
                      "sample_status": {
                        "$ref": "#/components/schemas/SampleStatus"
                      }
                    }
                  }
                },
                "examples": {
                  "Success": {
                    "description": "",
                    "value": [
                      {
                        "kit_id": "SPOTABCDEF",
                        "kit_type": "health_kit_1",
                        "order_id": "O1A2B3C4D5",
                        "kit_status": "received",
                        "sample_status": "received"
                      }
                    ]
                  },
                  "No results": {
                    "description": "",
                    "value": []
                  }
                }
              }
            },
            "description": "Success"
          }
        }
      }
    },
    "/api/v2/kits/{public_id}/": {
      "get": {
        "operationId": "api_v2_get_kit",
        "description": "Returns an individual kit with the given kit id.",
        "parameters": [
          {
            "in": "path",
            "name": "public_id",
            "schema": {
              "type": "string"
            },
            "description": "ID of the kit to retrieve.",
            "required": true
          }
        ],
        "security": [
          {
            "tokenAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Kit"
                },
                "examples": {
                  "Complete kit": {
                    "description": "",
                    "value": {
                      "kit_id": "string",
                      "type": "string",
                      "status": "string",
                      "events": [
                        {
                          "status": "preparing",
                          "created": "2023-01-14T03:34:01.736Z"
                        }
                      ],
                      "shipment_to_customer": {
                        "tracking_number": "string",
                        "carrier": "string",
                        "created": "2023-01-14T03:34:01.736Z"
                      },
                      "registered_to": {
                        "patient_id": "string",
                        "first_name": "string",
                        "last_name": "string",
                        "date_of_birth": "2023-01-14",
                        "sex": "string",
                        "email": "string",
                        "phone": "string"
                      },
                      "sample": {
                        "sample_id": "string",
                        "status": "string",
                        "events": [
                          {
                            "status": "awaiting_collection",
                            "created": "2023-01-14T03:34:01.736Z"
                          }
                        ],
                        "type": "string",
                        "shipments": [
                          {
                            "tracking_number": "string",
                            "carrier": "string",
                            "created": "2023-01-14T03:34:01.736Z"
                          }
                        ],
                        "panel": "string",
                        "report": {
                          "report_id": "da8d7f03-61ae-499c-8cb4-fa8629e2dad8",
                          "results": [
                            {
                              "result_type": "blood",
                              "name": "string",
                              "time_collected": "2023-01-14T03:34:01.736Z",
                              "result": "string",
                              "unit_of_measure": "string",
                              "result_level": "string",
                              "range_minimum": "string",
                              "range_maximum": "string",
                              "comments": "string"
                            }
                          ],
                          "panel": "string",
                          "pdf": "string",
                          "txt": "string",
                          "individual": {
                            "patient_id": "string",
                            "first_name": "string",
                            "last_name": "string",
                            "date_of_birth": "2023-01-14",
                            "sex": "string",
                            "email": "string",
                            "phone": "string"
                          },
                          "date_collected": "2023-01-14T03:34:01.736Z",
                          "date_received": "2023-01-14T03:34:01.736Z"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BadRequest"
                }
              }
            },
            "description": "Bad request"
          },
          "404": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NotFound"
                }
              }
            },
            "description": "Not found"
          }
        }
      }
    },
    "/api/v2/orders/": {
      "get": {
        "operationId": "api_v2_list_orders",
        "description": "Get a list of your orders. Providing any query params will further filter the results to only those that match the query params.",
        "parameters": [
          {
            "in": "query",
            "name": "email",
            "schema": {
              "type": "string"
            },
            "description": "Only retrieve orders associated with this email address."
          },
          {
            "in": "query",
            "name": "first_name",
            "schema": {
              "type": "string"
            },
            "description": "Only retrieve orders associated with this first name."
          },
          {
            "in": "query",
            "name": "last_name",
            "schema": {
              "type": "string"
            },
            "description": "Only retrieve orders associated with this last name."
          },
          {
            "in": "query",
            "name": "phone",
            "schema": {
              "type": "string"
            },
            "description": "Only retrieve orders associated with this phone number."
          },
          {
            "in": "query",
            "name": "status",
            "schema": {
              "type": "string",
              "enum": [
                "canceled",
                "completed",
                "in_progress",
                "pending"
              ]
            },
            "description": "Only retrieve orders that have this status."
          },
          {
            "in": "query",
            "name": "results",
            "description": "Number of results to return.",
            "schema": {
              "type": "integer",
              "minimum": 1,
              "maximum": 100
            }
          },
          {
            "in": "query",
            "name": "offset",
            "description": "The initial index from which to return the results.",
            "schema": {
              "type": "integer",
              "minimum": 0
            }
          }
        ],
        "security": [
          {
            "tokenAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "order_id": {
                        "type": "string"
                      },
                      "status": {
                        "$ref": "#/components/schemas/OrderStatus"
                      },
                      "created": {
                        "type": "string",
                        "format": "date-time"
                      },
                      "recipient": {
                        "$ref": "#/components/schemas/Recipient"
                      }
                    }
                  }
                },
                "examples": {
                  "Success": {
                    "description": "",
                    "value": [
                      {
                        "kit_id": "SPOTABCDEF",
                        "kit_type": "health_kit_1",
                        "order_id": "O1A2B3C4D5",
                        "status": "in_progress",
                        "recipient": {
                          "first_name": "Alice",
                          "last_name": "Jones",
                          "email": "alice123@gmail.com",
                          "phone": "123456789",
                          "address": {
                            "street1": "123 Street Road",
                            "street2": "",
                            "city": "San Francisco",
                            "state": "CA",
                            "country": "US",
                            "zip": "12345"
                          }
                        }
                      }
                    ]
                  },
                  "No results": {
                    "description": "",
                    "value": []
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "operationId": "api_v2_create_order",
        "description": "Create an order for delivering kits to a client, which will be created with a status of 'pending'.The order will be created with the user making the request as the 'placed_by' user.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateOrder"
              }
            },
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/CreateOrder"
              }
            },
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/CreateOrder"
              }
            }
          },
          "required": true
        },
        "security": [
          {
            "tokenAuth": []
          }
        ],
        "responses": {
          "201": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateOrderResponse"
                }
              }
            },
            "description": ""
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BadRequest"
                }
              }
            },
            "description": ""
          }
        }
      }
    },
    "/api/v2/orders/{public_id}/": {
      "get": {
        "operationId": "api_v2_get_order",
        "description": "Retrieve a singular order matching the provided ID.",
        "parameters": [
          {
            "in": "path",
            "name": "public_id",
            "schema": {
              "type": "string"
            },
            "description": "The ID of the order to retrieve.",
            "required": true
          }
        ],
        "security": [
          {
            "tokenAuth": []
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Order"
                },
                "examples": {
                  "Success": {
                    "value": {
                      "order_id": "O1A2B3C4D5",
                      "created": "2023-01-14T04:30:11.222Z",
                      "status": "completed",
                      "recipient": {
                        "first_name": "Alice",
                        "last_name": "Jones",
                        "email": "alice123@gmail.com",
                        "phone": "123456789",
                        "address": {
                          "street1": "123 Street Road",
                          "street2": "",
                          "city": "San Francisco",
                          "state": "CA",
                          "country": "US",
                          "zip": "12345"
                        }
                      },
                      "kit_types": [
                        "health_kit_1"
                      ],
                      "kits": [
                        {
                          "kit_id": "SPOTABCDEF",
                          "type": "health_kit_1",
                          "status": "registered",
                          "events": [
                            {
                              "status": "preparing",
                              "created": "2023-01-01T04:30:11.222Z"
                            },
                            {
                              "status": "in_transit",
                              "created": "2023-01-02T04:30:11.222Z"
                            },
                            {
                              "status": "delivered",
                              "created": "2023-01-03T04:30:11.222Z"
                            },
                            {
                              "status": "registered",
                              "created": "2023-01-04T04:30:11.222Z"
                            }
                          ],
                          "shipment_to_customer": {
                            "tracking_number": "9400123456789999876500",
                            "carrier": "USPS",
                            "created": "2023-01-01T04:30:11.222Z"
                          },
                          "registered_to": {
                            "patient_id": "50d394e4-b32e-425a-8384-c13caad14429",
                            "first_name": "Alice",
                            "last_name": "Jones",
                            "date_of_birth": "1990-01-01",
                            "sex": "F",
                            "email": "alice123@gmail.com",
                            "phone": "123456789"
                          },
                          "sample": {
                            "sample_id": "SPOTABCDEF",
                            "status": "resulted",
                            "events": [
                              {
                                "status": "awaiting_collection",
                                "created": "2023-01-01T04:30:11.222Z"
                              },
                              {
                                "status": "in_transit",
                                "created": "2023-01-05T04:30:11.222Z"
                              },
                              {
                                "status": "delivered",
                                "created": "2023-01-06T04:30:11.222Z"
                              },
                              {
                                "status": "received",
                                "created": "2023-01-07T04:30:11.222Z"
                              },
                              {
                                "status": "resulted",
                                "created": "2023-01-08T04:30:11.222Z"
                              }
                            ],
                            "type": "adx100_2",
                            "shipments": [
                              {
                                "tracking_number": "string",
                                "carrier": "string",
                                "created": "2023-01-14T04:30:11.222Z"
                              }
                            ],
                            "panel": "example_panel",
                            "report": {
                              "report_id": "a6107e6d-cfe3-4ba8-8a3e-6b68aabcc7b1",
                              "results": [
                                {
                                  "result_type": "quantity",
                                  "name": "HDL Cholesterol",
                                  "time_collected": "2023-01-14T04:30:11.222Z",
                                  "result": 123,
                                  "unit_of_measure": "mg/dL",
                                  "range_minimum": 20,
                                  "range_maximum": 200,
                                  "comments": null
                                },
                                {
                                  "result_type": "quantity",
                                  "name": "Vitamin B12",
                                  "time_collected": "2023-01-14T04:30:11.222Z",
                                  "result": "<10",
                                  "unit_of_measure": "pg/mL",
                                  "range_minimum": 20,
                                  "range_maximum": 200,
                                  "comments": null
                                },
                                {
                                  "result_type": "reactivity",
                                  "name": "Chlamydia",
                                  "time_collected": "2023-01-14T04:30:11.222Z",
                                  "result": "negative",
                                  "unit_of_measure": null,
                                  "range_minimum": null,
                                  "range_maximum": null,
                                  "comments": null
                                },
                                {
                                  "result_type": "DNA",
                                  "name": "rs1234567",
                                  "time_collected": "2023-01-14T04:30:11.222Z",
                                  "result": "TT",
                                  "unit_of_measure": null,
                                  "range_minimum": null,
                                  "range_maximum": null,
                                  "comments": null
                                }
                              ],
                              "pdf": "https://app.spotkits.com/results/f0e5a607-5b52-4d7c-a3f2-c40772d41482.pdf",
                              "txt": "https://app.spotkits.com/results/f0e5a607-5b52-4d7c-a3f2-c40772d41482.txt",
                              "date_collected": "2023-01-14T04:30:11.223Z",
                              "date_received": "2023-01-14T04:30:11.223Z",
                              "is_amendment": false
                            }
                          }
                        }
                      ]
                    }
                  }
                }
              }
            },
            "description": ""
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BadRequest"
                }
              }
            }
          },
          "404": {
            "description": "Order not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NotFound"
                }
              }
            }
          }
        }
      }
    },
    "/api/v2/tokens/patient_registration/": {
      "post": {
        "operationId": "api_v2_create_patient_token",
        "description": "Generate a one-time-use registration token for a patient with a lifetime of 10 minutes.",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreatePatientRegistrationToken"
              }
            },
            "application/x-www-form-urlencoded": {
              "schema": {
                "$ref": "#/components/schemas/CreatePatientRegistrationToken"
              }
            },
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/CreatePatientRegistrationToken"
              }
            }
          },
          "required": true
        },
        "security": [
          {
            "tokenAuth": []
          }
        ],
        "responses": {
          "201": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PatientRegistrationTokenResponse"
                }
              }
            },
            "description": ""
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BadRequest"
                }
              }
            },
            "description": ""
          },
          "404": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/NotFound"
                }
              }
            },
            "description": ""
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Address": {
        "type": "object",
        "properties": {
          "street1": {
            "type": "string",
            "description": "Recipient's address."
          },
          "street2": {
            "description": "Second line of recipient's address.",
            "type": "string",
            "nullable": true
          },
          "city": {
            "type": "string",
            "description": "Recipient's city of residence."
          },
          "state": {
            "type": "string",
            "description": "Recipient's state of residence."
          },
          "country": {
            "type": "string",
            "description": "Recipient's country of residence.",
            "enum": [
              "US",
              "CA"
            ]
          },
          "zip": {
            "type": "string",
            "description": "Recipient's zip code."
          }
        },
        "required": [
          "city",
          "state",
          "street1",
          "zip"
        ]
      },
      "AssignKits": {
        "type": "object",
        "properties": {
          "order_id": {
            "type": "string"
          },
          "kit_ids": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "bypass_address_validation": {
            "type": "boolean"
          }
        },
        "required": [
          "kit_ids",
          "order_id"
        ]
      },
      "BadRequest": {
        "type": "object",
        "properties": {
          "error": {
            "type": "string",
            "readOnly": true
          }
        },
        "required": [
          "error"
        ]
      },
      "BuildKit": {
        "type": "object",
        "properties": {
          "kit_public_id": {
            "type": "string",
            "maxLength": 255
          },
          "sample_public_id": {
            "type": "string",
            "maxLength": 255
          },
          "tracking_number": {
            "type": "string",
            "maxLength": 255
          },
          "kit_type_public_id": {
            "type": "string",
            "maxLength": 255
          },
          "lot_public_id": {
            "type": "string",
            "maxLength": 255
          },
          "assemblers": {
            "type": "string",
            "maxLength": 255
          }
        },
        "required": [
          "kit_public_id",
          "kit_type_public_id",
          "sample_public_id",
          "tracking_number"
        ]
      },
      "CreateOrder": {
        "type": "object",
        "properties": {
          "kit_types": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "A list of all the kit types to place in the order."
          },
          "recipient": {
            "$ref": "#/components/schemas/Recipient"
          },
          "client_order_id": {
            "type": "string",
            "description": "Optional metadata field for client use."
          },
          "client_customer_id": {
            "type": "string",
            "description": "Optional metadata field for client use."
          }
        },
        "required": [
          "kit_types",
          "recipient"
        ]
      },
      "CreateOrderResponse": {
        "type": "object",
        "properties": {
          "kit_id": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "events": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": {}
            }
          },
          "shipment_to_customer": {
            "type": "object",
            "additionalProperties": {}
          },
          "registered_to": {
            "type": "object",
            "additionalProperties": {}
          },
          "panels": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "samples": {
            "type": "array",
            "items": {
              "type": "object",
              "additionalProperties": {}
            }
          }
        },
        "required": [
          "events",
          "kit_id",
          "panels",
          "registered_to",
          "samples",
          "shipment_to_customer",
          "status",
          "type"
        ]
      },
      "CreatePatient": {
        "type": "object",
        "properties": {
          "first_name": {
            "type": "string",
            "description": "The first name of the patient to be created."
          },
          "last_name": {
            "type": "string",
            "description": "The last name of the patient to be created."
          },
          "email": {
            "type": "string",
            "format": "email",
            "description": "The email of the patient to be created."
          },
          "phone": {
            "type": "string",
            "description": "Optional phone number of the patient to be created."
          },
          "sex": {
            "type": "string",
            "description": "The biological sex of the patient to be created."
          },
          "date_of_birth": {
            "type": "string",
            "format": "date",
            "description": "The date of birth of the patient to be created."
          }
        },
        "required": [
          "date_of_birth",
          "email",
          "first_name",
          "last_name",
          "sex"
        ]
      },
      "CreatePatientRegistrationToken": {
        "type": "object",
        "properties": {
          "patient_id": {
            "type": "string",
            "description": "UUID of the patient."
          }
        },
        "required": [
          "patient_id"
        ]
      },
      "Kit": {
        "type": "object",
        "properties": {
          "kit_id": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "status": {
            "type": "string"
          },
          "events": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/KitEvent"
            }
          },
          "shipment_to_customer": {
            "type": "object",
            "properties": {
              "tracking_number": {
                "type": "string"
              },
              "carrier": {
                "type": "string"
              },
              "created": {
                "type": "string",
                "format": "date-time"
              }
            }
          },
          "registered_to": {
            "type": "object",
            "properties": {
              "patient_id": {
                "type": "string"
              },
              "first_name": {
                "type": "string"
              },
              "last_name": {
                "type": "string"
              },
              "date_of_birth": {
                "type": "string",
                "format": "date"
              },
              "sex": {
                "type": "string"
              },
              "email": {
                "type": "string"
              },
              "phone": {
                "type": "string"
              }
            }
          },
          "sample": {
            "type": "object",
            "properties": {
              "sample_id": {
                "type": "string"
              },
              "status": {
                "type": "string"
              },
              "events": {
                "type": "array",
                "items": {
                  "$ref": "#/components/schemas/SampleEvent"
                }
              },
              "type": {
                "type": "string",
                "enum": [
                  "adx100",
                  "adx100_2",
                  "adx100_4",
                  "whatman903_10",
                  "dry_transport_swab",
                  "hemaspot_hf",
                  "saliva_3"
                ]
              },
              "shipments": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "tracking_number": {
                      "type": "string"
                    },
                    "carrier": {
                      "type": "string"
                    },
                    "created": {
                      "type": "string",
                      "format": "date-time"
                    }
                  }
                }
              },
              "panel": {
                "type": "string"
              },
              "report": {
                "$ref": "#/components/schemas/Report"
              }
            }
          }
        }
      },
      "KitEvent": {
        "type": "object",
        "properties": {
          "status": {
            "$ref": "#/components/schemas/KitStatus"
          },
          "created": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "KitStatus": {
        "type": "string",
        "description": "The new status of the kit.",
        "enum": [
          "preparing",
          "in_transit",
          "delivered",
          "delivery_exception",
          "registered",
          "cancelled"
        ]
      },
      "NotFound": {
        "type": "object",
        "properties": {
          "error": {
            "type": "string",
            "readOnly": true
          }
        },
        "required": [
          "error"
        ]
      },
      "Order": {
        "type": "object",
        "properties": {
          "order_id": {
            "type": "string"
          },
          "created": {
            "type": "string",
            "format": "date-time"
          },
          "status": {
            "$ref": "#/components/schemas/OrderStatus"
          },
          "recipient": {
            "$ref": "#/components/schemas/Recipient"
          },
          "kit_types": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "kits": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Kit"
            }
          }
        }
      },
      "OrderStatus": {
        "type": "string",
        "enum": [
          "pending",
          "in_progress",
          "completed",
          "canceled"
        ]
      },
      "PatientRegistrationTokenResponse": {
        "type": "object",
        "properties": {
          "token": {
            "type": "string",
            "readOnly": true
          }
        },
        "required": [
          "token"
        ]
      },
      "Recipient": {
        "type": "object",
        "properties": {
          "first_name": {
            "type": "string",
            "description": "Recipient's first name."
          },
          "last_name": {
            "type": "string",
            "description": "Recipient's last name."
          },
          "email": {
            "type": "string",
            "description": "Recipient's email."
          },
          "phone": {
            "type": "string",
            "description": "Recipient's phone number, as a string."
          },
          "address": {
            "$ref": "#/components/schemas/Address"
          }
        },
        "required": [
          "address",
          "email",
          "first_name",
          "last_name",
          "phone"
        ]
      },
      "Report": {
        "nullable": true,
        "type": "object",
        "properties": {
          "report_id": {
            "type": "string"
          },
          "results": {
            "description": "",
            "type": "array",
            "items": {
              "oneOf": [
                {
                  "$ref": "#/components/schemas/ResultQuantity"
                },
                {
                  "$ref": "#/components/schemas/ResultReactivity"
                },
                {
                  "$ref": "#/components/schemas/ResultDNA"
                }
              ]
            }
          },
          "pdf": {
            "type": "string",
            "format": "uri"
          },
          "txt": {
            "type": "string",
            "format": "uri"
          },
          "date_collected": {
            "type": "string",
            "format": "date-time"
          },
          "date_received": {
            "type": "string",
            "format": "date-time"
          },
          "is_amendment": {
            "type": "boolean"
          }
        }
      },
      "ResultQuantity": {
        "type": "object",
        "properties": {
          "result_type": {
            "type": "string",
            "enum": [
              "quantity"
            ]
          },
          "name": {
            "type": "string",
            "description": "The biomarker that was analyzed."
          },
          "time_collected": {
            "type": "string",
            "format": "date-time"
          },
          "result": {
            "description": "",
            "oneOf": [
              {
                "type": "string"
              },
              {
                "type": "number"
              }
            ]
          },
          "unit_of_measure": {
            "type": "string",
            "nullable": true
          },
          "range_minimum": {
            "type": "string",
            "minimum": 0
          },
          "range_maximum": {
            "type": "number",
            "minimum": 0
          },
          "comments": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "ResultReactivity": {
        "type": "object",
        "properties": {
          "result_type": {
            "type": "string",
            "enum": [
              "reactivity"
            ]
          },
          "name": {
            "type": "string",
            "description": "The biomarker that was analyzed."
          },
          "time_collected": {
            "type": "string",
            "format": "date-time"
          },
          "result": {
            "description": "",
            "type": "string",
            "enum": [
              "positive",
              "negative"
            ]
          },
          "unit_of_measure": {
            "type": "string",
            "nullable": true
          },
          "range_minimum": {
            "type": "number",
            "nullable": true
          },
          "range_maximum": {
            "type": "number",
            "nullable": true
          },
          "comments": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "ResultDNA": {
        "type": "object",
        "properties": {
          "result_type": {
            "type": "string",
            "enum": [
              "DNA"
            ]
          },
          "name": {
            "type": "string",
            "description": "The biomarker that was analyzed."
          },
          "time_collected": {
            "type": "string",
            "format": "date-time"
          },
          "result": {
            "description": "",
            "type": "string",
            "enum": [
              "TT",
              "GG",
              "CG",
              "AG",
              "CT",
              "CC",
              "AA",
              "AT",
              "AC",
              "TA",
              "TG",
              "TC",
              "GA",
              "GT",
              "GC",
              "CA"
            ]
          },
          "unit_of_measure": {
            "type": "string",
            "nullable": true
          },
          "range_minimum": {
            "type": "number",
            "nullable": true
          },
          "range_maximum": {
            "type": "number",
            "nullable": true
          },
          "comments": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "SampleEvent": {
        "type": "object",
        "properties": {
          "status": {
            "$ref": "#/components/schemas/SampleStatus"
          },
          "created": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "SampleStatus": {
        "type": "string",
        "description": "The new status of the sample.",
        "enum": [
          "awaiting_collection",
          "collection_exception",
          "delivery_exception",
          "delivered",
          "in_transit",
          "received",
          "resulted",
          "partially_resulted",
          "extra_quality_checks",
          "cancelled"
        ]
      },
      "UploadDnaResults": {
        "type": "object",
        "properties": {
          "sample_id": {
            "type": "string"
          },
          "results": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": [
          "results",
          "sample_id"
        ]
      },
      "UploadDnaResultsResponse": {
        "type": "object",
        "properties": {
          "report": {
            "type": "string"
          }
        },
        "required": [
          "report"
        ]
      }
    },
    "securitySchemes": {
      "tokenAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "Authorization",
        "description": "Token-based authentication with required prefix \"Token\""
      }
    }
  },
  "x-readme": {
    "explorer-enabled": true,
    "proxy-enabled": true,
    "samples-enabled": true
  }
}
